#nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: "API CoachTracker"
            description: "Documentation de l'API CoachTracker"
            version: 1.0.0

    areas:
        path_patterns: 
            - ^/api(?!/doc$)